Certification app component/certpkg/certpkg/unpackaged/objects/Associates__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Emp_Id__c</fullName>
        <label>Emp Id</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>usrLocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Associate</relationshipLabel>
        <relationshipName>Associate</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Associate</label>
    <nameField>
        <displayFormat>A-{0000000}</displayFormat>
        <label>Serial No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Associate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Certification app component/certpkg/certpkg/unpackaged/objects/Certificate__c.object
<CustomObject>
    <fields>
        <fullName>AssociateId__c</fullName>
        <label>AssociateId</label>
        <referenceTo>Associates__c</referenceTo>
        <relationshipLabel>Certificates</relationshipLabel>
        <relationshipName>Certificates</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CertName__c</fullName>
        <label>CertificateName</label>
        <referenceTo>CertificateMaster__c</referenceTo>
        <relationshipLabel>Certificates</relationshipLabel>
        <relationshipName>Certificates</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Completed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Planned</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Certificate</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Sr. No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Certification app component/certpkg/certpkg/unpackaged/objects/CertificateMaster__c.object
<CustomObject>
    <label>CertificateMaster</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CertificateMaster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Certification app component/certpkg/certpkg/unpackaged/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Certification app component/certpkg/certpkg/unpackaged/classes/TestCertificationCtrl.cls
@isTest
public class TestCertificationCtrl {
    
     static testMethod void validatenewUserReg() {
         
         Associates__c testAssoc = new Associates__c();
         testAssoc.Name__c = 'TestUser';
         testAssoc.Emp_Id__c = String.valueOf('123456');
         testAssoc.Email__c = 'testUser@cognizant.com';
         testAssoc.usrLocation__c = 'a0P2800000Afny0';
         
         CertificateMaster__c testCert = new CertificateMaster__c();
         testCert.Name = 'testCertificate';
         
         CertificateMaster__c testCert1 = new CertificateMaster__c();
         testCert1.Name = 'testCertificate1';
         
         Location__c testLoc = new Location__c();
         testLoc.Name = 'testLocation';
         
         Test.startTest();
         insert testAssoc;
         List<Associates__c> lsttest = [Select Id, Name__c, Email__c from Associates__c where Name__c = 'TestUser'];
         String id1 = lsttest[0].Id;
         String email = lsttest[0].Email__c;
         system.debug('id1:'+id1);
        
         CertificationDetailsCtrl.getLocations();
         CertificationDetailsCtrl.getCertificates();
         insert testCert;
         insert testCert1;
         
         List<CertificateMaster__c> lst1 = [Select Id from CertificateMaster__c where Name = 'testCertificate'];
         String id2 = lst1[0].Id;
         system.debug('id2:'+id2);
         
         List<CertificateMaster__c> lst2 = [Select Id from CertificateMaster__c where Name = 'testCertificate1'];
         String id3 = lst2[0].Id;
         system.debug('id3:'+id3);
         
         Certificate__c newcert = new Certificate__c();
         newcert.AssociateId__c = id1;
         newcert.CertName__c = id2;
         newcert.Status__c = 'Not Completed';
         insert newcert;
         system.debug('newCertEmail:'+newcert.AssociateId__r.Email__c);
         insert testLoc;          
         CertificationDetailsCtrl.newUserReg('TestUser', '123456', 'testUser@cognizant.com', 'a0P2800000Afny0');
         CertificationDetailsCtrl.checkSubmit('123456', '12345');
         CertificationDetailsCtrl.newUserReg('TestUser', '123458', 'testUser@cognizant.com', 'a0P2800000Afny0');
          CertificationDetailsCtrl.submitFinal(id3, email, 'Not Completed', '', '', '');
         CertificationDetailsCtrl.submitFinal(id2, email, 'Not Completed', '', '', '');
         CertificationDetailsCtrl.submitFinal(id2, 'testUser@cognizant.com', 'Not Applicable', '', '', '');
         CertificationDetailsCtrl.checkId('123456');
         CertificationDetailsCtrl.checkId('123457');
         CertificationDetailsCtrl.getLocations();
         CertificationDetailsCtrl.getCertificates();
         CertificationDetailsCtrl.checkStatus('testUser@cognizant.com');
         CertificationDetailsCtrl.checkStatus('testUser1@cognizant.com');
         CertificationDetailsCtrl.newUserReg('TestUser2', '123457', 'testUser2@cognizant.com', 'a0P2800000Afny0');
         delete testAssoc;
         delete testCert; 
         delete testLoc;         
         Test.stopTest();
         
     }


}